name: Auto Pull Request

on:
  push:
    branches:
      - 'feature/**'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          branch: ${{ github.ref_name }}
          title: "${{ github.event.head_commit.message }}"
          body: |
            PR criado automaticamente 🤖

            Branch: ${{ github.ref_name }}

            Revisar alterações antes do merge.
